### ISSUE TITLE
linfa-clustering won't compile due to type error

### ISSUE THREAD

**Issue by quietlychris** [rust-ml/linfa#126]
I came across an issue compiling `linfa-clustering` as a dependency for the Rust-ML book today, which per the error message is tracked down to a link the `linfa-clustering/src/gaussian_mixture/algorithm.rs` in the `compute_precisions_cholesky_full()` function, which using the Cholesky method [imported in](https://docs.rs/ndarray-linalg/0.13.1/ndarray_linalg/cholesky/index.html) from `ndarray-linalg`. As far as I can tell, when cloning linfa's `master` and trying to build in the sub-crate, I run into the same compilation error. I've tinkered around with it, but haven't figured out a fix quite yet.

```bash
Compiling linfa-clustering v0.3.1 (https://github.com/rust-ml/linfa?branch=master#b7c31c58)
error[E0599]: no method named `cholesky` found for struct `ArrayBase<ViewRepr<&<F as linfa::Float>::Lapack>, Dim<[usize; 2]>>` in the current scope
   --> /home/chrism/.cargo/git/checkouts/linfa-f557574ebcb8312b/b7c31c5/algorithms/linfa-clustering/src/gaussian_mixture/algorithm.rs:262:51
    |
262 |             let decomp = covariance.with_lapack().cholesky(UPLO::Lower)?;
    |                                                   ^^^^^^^^ method not found in `ArrayBase<ViewRepr<&<F as linfa::Float>::Lapack>, Dim<[usize; 2]>>`

error: aborting due to previous error
```

**Comment by bytesnake** [comment]
This was introduced in https://github.com/rust-ml/linfa/pull/121 and happens when you do not specify a LAPACK backend for compilation. I pushed a fix in https://github.com/rust-ml/linfa/commit/686645035a9a4803da6d70f2e2150a2f1f082863

**Comment by quietlychris** [comment]
Sounds great, thanks!
