### PR TITLE
Update ndarray 0.14

### PR DESCRIPTION
**Pull request by relf**
This PR update linfa to ndarray 0.14 version with the following crates updates as well
* approx = 0.4
* argmin = 0.4
* ndarray-csv = 0.5
* ndarray-linalg = 0.13
* ndarray-npy = 0.7
* ndarray-rand = 0.13
* ndarray-stats = 0.4
* num-traits = 0.2
* rand = 0.8
* rand-isaac = 0.3
* sprs = git master rev=761d4f0

The PR is still WIP as there is an issue with sprs 0.10 (see #109 )

### CODE REVIEW

File: algorithms/linfa-clustering/src/gaussian_mixture/algorithm.rs [hunk 1]
```diff
@@ -293,7 +293,7 @@ impl<F: Float + Lapack + Scalar> GaussianMixtureModel<F> {
         let n_samples = observations.nrows();
         let (weights, means, covariances) = Self::estimate_gaussian_parameters(
             &observations,
-            &log_resp.mapv(|v| v.exp()),
+            &log_resp.mapv(|v| Scalar::exp(v)),
```
Comment (bytesnake) [inline algorithms/linfa-clustering/src/gaussian_mixture/algorithm.rs:296]: can you import the trait and use the original order? There are several places where this becomes really long

File: algorithms/linfa-clustering/src/gaussian_mixture/algorithm.rs [hunk 2]
```diff
@@ -596,7 +596,7 @@ mod tests {
         assert!(
             match gmm.expect_err("should generate an error with reg_covar being nul") {
                 GmmError::LinalgError(e) => match e {
-                    LinalgError::Lapack { return_code: 1 } => true,
+                    LinalgError::Lapack(_) => true,
```
Comment (bytesnake) [inline algorithms/linfa-clustering/src/gaussian_mixture/algorithm.rs:599]: you have to check of the `return_code` here

File: algorithms/linfa-clustering/src/k_means/algorithm.rs [hunk 3]
```diff
@@ -365,7 +365,7 @@ fn get_random_centroids<F: Float, D: Data<Elem = F>>(
 mod tests {
     use super::*;
     use approx::assert_abs_diff_eq;
-    use ndarray::{array, stack, Array, Array1, Array2, Axis};
+    use ndarray::{array, concatenate, Array, Array1, Array2, Axis};
```
Comment (bytesnake) [inline algorithms/linfa-clustering/src/k_means/algorithm.rs:368]: `concatenate` is really long, I don't know why they didn't go for the abbreviation `concat`

File: algorithms/linfa-kernel/Cargo.toml [hunk 4]
```diff
@@ -24,8 +24,9 @@ default-features = false
 features = ["std", "derive"]
 
 [dependencies]
-ndarray = "0.13"
-sprs = { version = "0.9.3", default-features = false }
+ndarray = "0.14"
+num-traits = "0.2"
+sprs = { git="https://github.com/vbarrielle/sprs.git", rev="761d4f0", default-features = false }
```
Comment (bytesnake) [inline algorithms/linfa-kernel/Cargo.toml:29]: didn't know that you can specify the commit hash in your dependency tree :) to what revision does this point, I assume the `linfa-kernel` would not compile with the latest `sprs` release?

File: algorithms/linfa-linear/Cargo.toml [hunk 5]
```diff
@@ -17,16 +17,16 @@ keywords = ["machine-learning", "linfa", "ai", "ml", "linear"]
 categories = ["algorithms", "mathematics", "science"]
 
 [dependencies]
-ndarray = {version = "0.13", features = ["blas", "approx"]}
-ndarray-linalg = "0.12"
-ndarray-stats = "0.3"
+ndarray = {version = "0.14", features = ["blas", "approx"]}
```
Comment (bytesnake) [inline algorithms/linfa-linear/Cargo.toml:20]: if you're correcting the spacing, do here as well. I actually don't know why rustfmt doesn't do that automatically

File: algorithms/linfa-reduction/src/pca.rs [hunk 6]
```diff
@@ -293,7 +293,7 @@ mod tests {
             let mp_law = ((b - x) * (x - a)).sqrt() / std::f64::consts::PI / x;
             let empirical = count as f64 / 500. / ((2.8 - 0.1) / 28.);
 
-            assert_abs_diff_eq!(mp_law, empirical, epsilon = 0.05);
+            assert_abs_diff_eq!(mp_law, empirical, epsilon = 0.06);
```
Comment (bytesnake) [inline algorithms/linfa-reduction/src/pca.rs:296]: this fails for you? The test should be deterministic

**Review by bytesnake — COMMENTED** [review]
Thanks for the cleanup and dependency update. This won't work with the latest `sprs` release because of https://github.com/vbarrielle/sprs/issues/278 correct? The `0.14` -> `0.15` jump seems to be quite big (I just skimmed the release notes, there are probably some breakages for the parallel stuff in kmeans) and should be in a separate crate

File: algorithms/linfa-clustering/src/gaussian_mixture/algorithm.rs (hunk 1 above)
Comment (relf) [reply algorithms/linfa-clustering/src/gaussian_mixture/algorithm.rs:296]: I am not sure to understand... What do you mean by the original order? Here if I use `v.exp()` I get the following compilation error:
```bash
   Compiling linfa-clustering v0.3.1 (D:\rlafage\workspace\linfa\algorithms\linfa-clustering)
error[E0034]: multiple applicable items in scope
    --> algorithms\linfa-clustering\src\gaussian_mixture\algorithm.rs:296:34
     |
296  |             &log_resp.mapv(|v| v.exp()),
     |                                  ^^^ multiple `exp` found
     |
note: candidate #1 is defined in the trait `ndarray_rand::rand_distr::num_traits::Float`
    --> D:\rlafage\.cargo\registry\src\github.com-1ecc6299db9ec823\num-traits-0.2.14\src\float.rs:1336:5
     |
1336 |     fn exp(self) -> Self;
     |     ^^^^^^^^^^^^^^^^^^^^^
note: candidate #2 is defined in the trait `Scalar`
    --> D:\rlafage\.cargo\registry\src\github.com-1ecc6299db9ec823\cauchy-0.3.0\src\lib.rs:112:5
     |
112  |     fn exp(self) -> Self;
     |     ^^^^^^^^^^^^^^^^^^^^^
help: disambiguate the associated function for candidate #1
     |
296  |             &log_resp.mapv(|v| ndarray_rand::rand_distr::num_traits::Float::exp(v)),
     |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
help: disambiguate the associated function for candidate #2
     |
296  |             &log_resp.mapv(|v| Scalar::exp(v)),
     |                                ^^^^^^^^^^^^^^
```

File: algorithms/linfa-kernel/Cargo.toml (hunk 4 above)
Comment (relf) [reply algorithms/linfa-kernel/Cargo.toml:29]: Yes, `linfa-kernel` can not compile with `sprs 0.10`, my question was: could we release linfa 0.4 using such spec or is it too bold? Sure I would prefer a `sprs 0.10.1` fixing the issue but atm it blocks the ndarray upgrade.

File: algorithms/linfa-reduction/src/pca.rs (hunk 6 above)
Comment (relf) [reply algorithms/linfa-reduction/src/pca.rs:296]: Yes I had to adjust the epsilon, I supposed some subtle computation changes in the dependencies? I will check what I get currently.

File: algorithms/linfa-clustering/src/gaussian_mixture/algorithm.rs (hunk 2 above)
Comment (relf) [reply algorithms/linfa-clustering/src/gaussian_mixture/algorithm.rs:599]: You're right, I took a shortcut, Lapack error has changed, I will check

**Comment by relf** [comment]
> This won't work with the latest sprs release because of vbarrielle/sprs#278 correct?

Exactly. I open the `sprs` issue after I get a compilation error with `linfa-kernel`.

File: algorithms/linfa-clustering/src/gaussian_mixture/algorithm.rs (hunk 2 above)
Comment (relf) [reply algorithms/linfa-clustering/src/gaussian_mixture/algorithm.rs]: done

File: algorithms/linfa-linear/Cargo.toml (hunk 5 above)
Comment (relf) [reply algorithms/linfa-linear/Cargo.toml]: done

File: algorithms/linfa-clustering/src/gaussian_mixture/algorithm.rs (hunk 1 above)
Comment (bytesnake) [reply algorithms/linfa-clustering/src/gaussian_mixture/algorithm.rs:296]: ah I see, these are conflicting because the first exponential is real only and the second is complex. I was confused by the name `Scalar` representing the complex as well as real numbers. Any idea why this ambiguity appears now?

File: algorithms/linfa-clustering/src/gaussian_mixture/algorithm.rs (hunk 2 above)
Comment (bytesnake) [reply algorithms/linfa-clustering/src/gaussian_mixture/algorithm.rs]: you can also click on `Resolve conversation`

File: algorithms/linfa-kernel/Cargo.toml (hunk 4 above)
Comment (bytesnake) [reply algorithms/linfa-kernel/Cargo.toml:29]: no that is not possible, because `crates.io` only allows self referencing and we would therefore not be able to publish the crate when using a foreign git source. We can't go forward without `sprs` fixing and publishing their crate.

File: algorithms/linfa-clustering/src/gaussian_mixture/algorithm.rs (hunk 1 above)
Comment (relf) [reply algorithms/linfa-clustering/src/gaussian_mixture/algorithm.rs:296]: After a bit of digging, I found that `ndarray-linalg` undergoes the same phenomenon : https://github.com/rust-ndarray/ndarray-linalg/commit/5157b22b0d3c911da7ad25f93037cd24dcc476f1 which led me to compare cauchy 0.2 vs 0.3 https://github.com/rust-math/cauchy/compare/0.2.2...0.3.0 and it seems that operations like `exp()` were changed to take `self` (instead of `&self`) which could explain the ambiguity is popping up now.

File: algorithms/linfa-clustering/src/gaussian_mixture/algorithm.rs (hunk 2 above)
Comment (relf) [reply algorithms/linfa-clustering/src/gaussian_mixture/algorithm.rs]: Yeah, I always tend to feel that the conversation should be resolved by the reviewer.

**Comment by relf** [comment]
Hmmm... I do not understand what is going on. I am not familiar with the various CI checks. :eyes: It seems that build fails with rustc 1.42 which would be our current lowest rustc supported version, @bytesnake correct?

**Comment by mulimoen** [comment]
Running `cargo tree --all -i ndarray` shows you are pulling in `ndarray:0.15.1` through
```
ndarray v0.15.1
└── ndarray-rand v0.14.0
    └── argmin v0.4.2
        ├── linfa-linear v0.3.1 (/home/magnus/Documents/projects/linfa/algorithms/linfa-linear)
        └── linfa-logistic v0.3.1 (/home/magnus/Documents/projects/linfa/algorithms/linfa-logistic)
```

**Comment by relf** [comment]
@mulimoen thanks for the heads up. Indeed in the meantime, `argmin` bumped from 0.4.1 to 0.4.2 pulling new `ndarray_rand` version and then new `ndarray 0.15`! At the same time  `argmin 0.4.2` fixes the issue https://github.com/argmin-rs/argmin/issues/104 which broke the `linfa` CI system! I am doomed! :sweat_smile:

**Comment by mulimoen** [comment]
@relf Ouch, that is quite unfortunate, you were almost there with the `sprs` bump

**Review by bytesnake — APPROVED** [review]
okay let's bump and I will try to clean up a bit in a follow up :+1:
